/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode : 'class',
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#dbe1ff",
        "inverse-on-surface": "#313030",
        "primary-container": "#c4a44d",
        "secondary-container": "#b89a3d",
        "outline-variant": "#4d4635",
        "on-surface": "#e5e2e1",
        "tertiary-fixed-dim": "#b4c5ff",
        "tertiary-container": "#97b0ff",
        "on-error": "#690005",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-highest": "#353534",
        "surface-container-high": "#2a2a2a",
        "on-error-container": "#ffdad6",
        "surface-container": "#201f1f",
        "on-primary-fixed-variant": "#574500",
        "error-container": "#93000a",
        "on-secondary-fixed": "#241a00",
        "on-secondary": "#3d2e00",
        "surface-bright": "#393939",
        "primary-fixed": "#f2db9d",
        "surface": "#131313",
        "on-tertiary-fixed": "#00174b",
        "error": "#ffb4ab",
        "outline": "#99907c",
        "on-primary-container": "#4a3b00",
        "surface-tint": "#c9ae5d",
        "on-primary": "#2d2400",
        "on-background": "#e5e2e1",
        "primary-fixed-dim": "#c9ae5d",
        "secondary-fixed": "#f2db9d",
        "on-secondary-fixed-variant": "#584400",
        "surface-variant": "#353534",
        "background": "#131313",
        "surface-container-low": "#1c1b1b",
        "on-secondary-container": "#503d00",
        "secondary-fixed-dim": "#d4b863",
        "surface-dim": "#131313",
        "on-surface-variant": "#d0c5af",
        "on-tertiary": "#082b72",
        "on-tertiary-fixed-variant": "#27438a",
        "secondary": "#d4b863",
        "tertiary": "#bfcdff",
        "on-primary-fixed": "#241a00",
        "primary": "#c9ae5d",
        "inverse-surface": "#e5e2e1",
        "inverse-primary": "#735c00",
        "on-tertiary-container": "#254188"
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
